name       : curaengine
version    : 3.4.1
release    : 8
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/3.4.1.tar.gz : 478164dec9a71a3c3b044c660b8186ced01c7bf638a5976f6ea61424336f2aed
license    : AGPL-3.0
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
