name       : curaengine
version    : 3.0.3
release    : 2
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/3.0.3.tar.gz : a8e9b99b42844dce1516c21e4d46bc40e17afbb3abec9ef92f3bb352d3cb12fb
license    : AGPL-3.0
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
