name       : curaengine
version    : 4.8.0
release    : 22
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.8.0.tar.gz : 752977fbe48653743b9f1a6e25e6d1f061513b7cf1cd4f0105b233595e8a15ff
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(polyclipping)
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake . -DUSE_SYSTEM_LIBS=ON
build      : |
    %make
install    : |
    %make_install
