name       : curaengine
version    : 4.2.0
release    : 14
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.2.0.tar.gz : 9e66c2840c46ad5ba91da872d73cc8d8d03bf163fe8ce9a81ec5188a6d7b4593
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
