name       : curaengine
version    : 3.3.0
release    : 6
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/3.3.0.tar.gz : a8fd7deb505771d2e7cf3a2c2d7e78479f59e001a990374ed505030804dc71fc
license    : AGPL-3.0
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
