name       : curaengine
version    : 3.6.0
release    : 11
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/3.6.0.tar.gz : e44930b3a7853935fc12afa8b93bccc75a2e446a9deab36f372341bb8ce9339e
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
