name       : curaengine
version    : 4.3.0
release    : 15
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.3.0.tar.gz : 4922a21ae90f95daae918baf21b51d94e36b8aac8e160b73c8088b993dd78ccb
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(polyclipping)
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake . -DUSE_SYSTEM_LIBS=ON
build      : |
    %make
install    : |
    %make_install
