name       : curaengine
version    : 4.4.1
release    : 16
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/v4.4.1.tar.gz : 6881262902405f8ad8732d9098ddf796cd0e5b23ff3c09e4d0af47d55eadab83
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(polyclipping)
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake . -DUSE_SYSTEM_LIBS=ON
build      : |
    %make
install    : |
    %make_install
