name       : curaengine
version    : 4.0.0
release    : 12
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.0.0.tar.gz : 08c8cc6ca6ba44ce35cf66b06e399408dd5fc809a208afc1892f0f700728326e
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
