name       : curaengine
version    : 4.10.0
release    : 24
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.10.0.tar.gz : bbc931251c89f68b8670cd0e5a06b81fde99a5e440bdbfe0e7efc3a749642157
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(polyclipping)
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake . -DUSE_SYSTEM_LIBS=ON
build      : |
    %make
install    : |
    %make_install
