name       : curaengine
version    : 3.5.1
release    : 9
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/3.5.1.tar.gz : 1edabbc520f2a331394d5db82a951c258da7d8827c0fa9188e77d735250530e8
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D
    models into 3D printing instruction for Ultimaker and other GCode based
    3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
