name       : curaengine
version    : 4.9.1
release    : 23
source     :
    - https://github.com/Ultimaker/CuraEngine/archive/4.9.1.tar.gz : eb422ef388bee09d26bbf3bade489359bf1fd59fd04d8452ac5d6ab3ba5e3894
license    : AGPL-3.0-or-later
component  : programming
summary    : Engine for processing 3D models into G-code instructions for 3D printers
description: |
    CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers. It is part of the larger open source project called "Cura".
builddeps  :
    - pkgconfig(RapidJSON)
    - pkgconfig(polyclipping)
    - pkgconfig(protobuf)
    - libarcus-devel
    - stb
setup      : |
    %cmake . -DUSE_SYSTEM_LIBS=ON
build      : |
    %make
install    : |
    %make_install
